version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  build:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.0.3-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: twilinks
          RAILS_ENV: test
      - image: cimg/postgres:12.8
        environment:
          POSTGRES_USER: twilinks
          POSTGRES_DB: twilinks_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
          
      - run: gem install bundler

      - run:
          name: Update bundler
          command: gem update bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: rubocop
          command: bundle exec rubocop -c .rubocop.yml

      - run:
          name: Lint
          command: bundle exec slim-lint app/views -c config/slim_lint.yml

      - run:
          name: Database setup
          command: bundle exec rake db:schema:load

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: Rails test
          command: bundle exec rspec
